- name: Get SQL files between versions for prod
  id: sql_range
  run: |
    current="1.1.22"
    target="1.1.29"

    echo "Files between $current and $target:"
    
    selected_files=$(find sql -type f -name "V*.sql" | while read file; do
      version=$(basename "$file" | sed -n 's/^V\([0-9.]\+\)__.*$/\1/p')
      # Compare versions using sort -V
      if [[ "$(printf "%s\n" "$current" "$version" | sort -V | tail -n1)" == "$version" ]] && \
         [[ "$(printf "%s\n" "$target" "$version" | sort -V | head -n1)" == "$version" ]] && \
         [[ "$version" != "$current" ]]; then
        echo "$file"
      fi
    done)

    echo "$selected_files"
    
    # Save to file or GitHub output
    echo "$selected_files" > filtered_files.txt
    echo "files=$selected_files" >> "$GITHUB_OUTPUT"



- name: Upload filtered SQL files to S3
  run: |
    while IFS= read -r file; do
      echo "Uploading $file..."
      aws s3 cp "$file" "s3://sri031901/$file"
    done < filtered_files.txt