name: Detect Changed Files in Folder

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history (required for git diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important! So git has the full history

      - name: Get changed files in flyway/ folder
        id: detect
        run: |
          echo "Previous commit: ${{ github.event.before }}"
          echo "Current commit: ${{ github.sha }}"

          # Default to HEAD~1 if github.event.before is empty (e.g., first push)
          BEFORE_COMMIT=${{ github.event.before }}
          if [ -z "$BEFORE_COMMIT" ]; then
            BEFORE_COMMIT=$(git rev-parse HEAD~1)
          fi

          # Get changed files in flyway/ folder
          git diff --name-only "$BEFORE_COMMIT" ${{ github.sha }} | grep '^sql/' > changed_files.txt || true

          echo "Changed files:"
          cat changed_files.txt || echo "No files found"

          # Export comma-separated list
          FILES=$(paste -sd "," changed_files.txt || echo "")
          echo "files_changed=$FILES" >> $GITHUB_OUTPUT

      - name: Print changed files
        run: |
          echo "Changed files: ${{ steps.detect.outputs.files_changed }}"
