name: Upload new SQL files to S3-AWS-2

on:
  push:
    paths:
      - 'sql/**'

jobs:
  upload-new-sql-files:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1  # change to your region

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get added SQL files only
        id: detect
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --diff-filter=A --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^sql/.*\.sql$' > added_files.txt || true
          
          if [[ -s added_files.txt ]]; then
            echo "files_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload added SQL files to S3
        if: steps.detect.outputs.files_changed == 'true'
        run: |
          while IFS= read -r file; do
            echo "Uploading $file to S3..."
            aws s3 cp "$file" "s3://sri-02242025/$file"
          done < added_files.txt